export const GET_RECIPES = "GET_RECIPES"
export const GET_ID_RECIPE = "GET_ID_RECIPE"
export const GET_NAME_RECIPES = "GET_NAME_RECIPES"
export const GET_DIETS = "GET_DIETS"
export const FILTER_BY_DIET = "FILTER_BY_DIET"
export const SORT_BY_NAME = "SORT_BY_NAME"
export const SORT_BY_HEALTH = "SORT_BY_HEALTH"
export const POST_RECIPE = "POST_RECIPE"